### ISSUE TITLE
Diversify geography & language of acceptance tests

### ISSUE THREAD

**Issue by riordan** [pelias/acceptance-tests#129] opened 2015-07-27 12:14 UTC
Tests are very New-Yorky. Not that it's a bad thing to have adequate coverage of *the greatest city in the world*, but we should expand the test set to be more broadly representative and globally inclusive.

**Comment by orangejulius** [comment] 2015-07-30 14:05
:+1:

**Comment by missinglink** [comment] 2015-10-08 16:45
see: https://github.com/pelias/api/blob/master/test/unit/helper/labelGenerator.js for some international places

**Comment by orangejulius** [comment] 2016-01-12 19:35
Let's call this a dupe of pelias/pelias#196

**Closed by orangejulius** 2016-01-12 19:35 UTC
Labels: enhancement, story
