### ISSUE TITLE
[discussion] colours

### ISSUE THREAD

**Issue by missinglink** [pelias/acceptance-tests#52] opened 2015-05-21 11:59 UTC
just wondering why errors are yellow and regressions are red?

I would expect errors to be red because they are serious problems, the minor regressions such as changes in ordering of results should be yellow.

would anyone object to me changing red/yellow around?

![colours](http://peter.johnson.s3.amazonaws.com/colours.png)

**Comment by dianashk** [comment] 2015-05-21 13:31
`yellow` is for expected failures. It’s tests that we know are failing and will get around to fixing. But they don't require us to stop the presses or revert code, since they weren't working to begin with. Occasionally you’ll see an improvement label on those tests that were expected to fail but are now passing.

`red` is reserved for tests that are expected to pass but are failing, because those are the tests that require immediate attention. We currently don't differentiate between different types of regressions. Basically if the result is not found or is not found within the expected threshold, we flag it as a regression.
I think ordering can be indicative of a problem and warrants an investigation. If we see that it is in fact insignificant, we can just change the `priorityThresh` value for the test case.

This isn't a perfect system and proposals for changes are welcome.

**Comment by dianashk** [comment] 2015-06-15 15:00
@missinglink, @orangejulius has made a lot of changes to the framework. We will no longer have yellow or blue. Can this issue be closed?

**Comment by orangejulius** [comment] 2015-06-25 18:16
Moving this back to on deck, I'll work on it soon.

My plan is to remove the fail state entirely, so that we can only have pass, placeholder, and regressions. I'll change the color to red for regressions as well.

**Comment by orangejulius** [comment] 2015-08-03 19:12
pelias/fuzzy-tester#5 would resolve this by getting rid of the fail state

**Closed** 2015-08-14 19:59 UTC
